baseurl = "https://shrektan.com"
languageCode = "zh-cn"
title = "Xianying's Blog"
theme = "hugo-xmin"
googleAnalytics = "UA-68366586-1"
disqusShortname = ""
ignoreFiles = ["_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true
hasCJKLanguage = true


[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页/Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于/About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "类别/Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签/Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅/Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo."
    footer = "&copy; [Xianying Tan](https://blog.shrektan.com) 2017 -- 2021 | [Github](https://github.com/shrektan)"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "11.3.1"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "default"
    
    GithubEdit = "https://github.com/shrektan/shrektan_blog/edit/master/content/"

[params.giscus]
    repo = ""
    repoID = ""
    category = "Announcements"
    categoryID = ""
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "preferred_color_scheme"
    lang = "en"
    loading = "lazy"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
