baseurl = "https://shrektan.com"
title = "Xianying's Blog"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents = "↩"
enableEmoji = true
hasCJKLanguage = true

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[languages]
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-cn"
    weight = 1
    [languages.zh.params]
      description = "谭显英的个人博客"
      footer = "&copy; [谭显英](https://shrektan.com) 2017 -- 2025 | [Github](https://github.com/shrektan)"
    [[languages.zh.menu.main]]
      name = "主页"
      url = "/"
      weight = 1
    [[languages.zh.menu.main]]
      name = "关于"
      url = "/about/"
      weight = 2
    [[languages.zh.menu.main]]
      name = "类别"
      url = "/categories/"
      weight = 3
    [[languages.zh.menu.main]]
      name = "标签"
      url = "/tags/"
      weight = 4
    [[languages.zh.menu.main]]
      name = "订阅"
      url = "/index.xml"
      weight = 5

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 2
    [languages.en.params]
      description = "Xianying Tan's personal blog"
      footer = "&copy; [Xianying Tan](https://shrektan.com) 2017 -- 2025 | [Github](https://github.com/shrektan)"
    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Categories"
      url = "/categories/"
      weight = 3
    [[languages.en.menu.main]]
      name = "Tags"
      url = "/tags/"
      weight = 4
    [[languages.en.menu.main]]
      name = "Subscribe"
      url = "/index.xml"
      weight = 5

[params]
    highlightjsVersion = "11.3.1"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "default"
    GithubEdit = "https://github.com/shrektan/shrektan_blog/edit/master/content/"

[params.giscus]
    repo = "shrektan/shrektan_blog"
    repoID = "MDEwOlJlcG9zaXRvcnkxMTkyNDkyNTU="
    category = "Comments"
    categoryID = "DIC_kwDOBxuZZ84C2pup"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "preferred_color_scheme"
    loading = "lazy"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
